-- =====================================================
-- FILE: 08_business_analysis.sql
-- PROJECT: SQL Data Analytics Project
-- DESCRIPTION: Business insight and analytical queries
-- TOTAL QUERIES: 15
-- =====================================================

-- 1. Top selling product based on quantity sold
SELECT p.product_name,
       SUM(oi.quantity) AS total_quantity_sold
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 1;

-- 2. Top 5 selling products
SELECT p.product_name,
       SUM(oi.quantity) AS total_sold
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC
LIMIT 5;

-- 3. Total revenue generated by each product
SELECT p.product_name,
       SUM(oi.quantity * p.price) AS total_revenue
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- 4. Customer who placed the most orders
SELECT c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC
LIMIT 1;

-- 5. Top 3 customers by number of orders
SELECT c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC
LIMIT 3;

-- 6. City with the highest number of customers
SELECT city,
       COUNT(customer_id) AS total_customers
FROM Customers
GROUP BY city
ORDER BY total_customers DESC
LIMIT 1;

-- 7. City with the highest number of orders
SELECT c.city,
       COUNT(o.order_id) AS total_orders
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY total_orders DESC
LIMIT 1;

-- 8. Department with the highest salary expense
SELECT d.dept_name,
       SUM(e.salary) AS total_salary
FROM Departments d
JOIN Employees e ON d.dept_id = e.dept_id
GROUP BY d.dept_name
ORDER BY total_salary DESC
LIMIT 1;

-- 9. Average salary by department
SELECT d.dept_name,
       AVG(e.salary) AS average_salary
FROM Departments d
JOIN Employees e ON d.dept_id = e.dept_id
GROUP BY d.dept_name;

-- 10. Highest paid employee
SELECT emp_name, salary
FROM Employees
ORDER BY salary DESC
LIMIT 1;

-- 11. Employees earning above company average
SELECT emp_name, salary
FROM Employees
WHERE salary > (
    SELECT AVG(salary)
    FROM Employees
);

-- 12. Products generating revenue greater than 50000
SELECT p.product_name,
       SUM(oi.quantity * p.price) AS revenue
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
HAVING revenue > 50000;

-- 13. Total orders placed each month
SELECT MONTH(order_date) AS order_month,
       COUNT(order_id) AS total_orders
FROM Orders
GROUP BY order_month
ORDER BY order_month;

-- 14. Customers who ordered electronics products
SELECT DISTINCT c.customer_name
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE p.category = 'Electronics';

-- 15. Total revenue generated per city
SELECT c.city,
       SUM(oi.quantity * p.price) AS total_revenue
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
GROUP BY c.city
ORDER BY total_revenue DESC;
