-- =====================================================
-- FILE: 10_advanced_data_analysis.sql
-- PROJECT: SQL Data Analytics Project
-- DESCRIPTION: Advanced analytical SQL queries
-- TOTAL QUERIES: 15
-- =====================================================

-- 1. Total revenue generated by the company
SELECT SUM(oi.quantity * p.price) AS total_company_revenue
FROM Order_Items oi
JOIN Products p ON oi.product_id = p.product_id;


-- 2. Revenue generated by each product category
SELECT p.category,
       SUM(oi.quantity * p.price) AS category_revenue
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY category_revenue DESC;


-- 3. Revenue generated by each product
SELECT p.product_name,
       SUM(oi.quantity * p.price) AS product_revenue
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY product_revenue DESC;


-- 4. Top 5 revenue generating products
SELECT p.product_name,
       SUM(oi.quantity * p.price) AS revenue
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 5;


-- 5. Revenue generated by each city
SELECT c.city,
       SUM(oi.quantity * p.price) AS city_revenue
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
GROUP BY c.city
ORDER BY city_revenue DESC;


-- 6. Customer with highest spending
SELECT c.customer_name,
       SUM(oi.quantity * p.price) AS total_spending
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY total_spending DESC
LIMIT 1;


-- 7. Top 5 customers by total spending
SELECT c.customer_name,
       SUM(oi.quantity * p.price) AS total_spending
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY total_spending DESC
LIMIT 5;


-- 8. Monthly revenue trend
SELECT MONTH(o.order_date) AS month,
       SUM(oi.quantity * p.price) AS monthly_revenue
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
GROUP BY month
ORDER BY month;


-- 9. Most frequently ordered product
SELECT p.product_name,
       COUNT(oi.order_id) AS order_frequency
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY order_frequency DESC
LIMIT 1;


-- 10. Product with highest total quantity sold
SELECT p.product_name,
       SUM(oi.quantity) AS total_quantity
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC
LIMIT 1;


-- 11. Department salary ranking
SELECT d.dept_name,
       SUM(e.salary) AS total_salary_expense
FROM Departments d
JOIN Employees e ON d.dept_id = e.dept_id
GROUP BY d.dept_name
ORDER BY total_salary_expense DESC;


-- 12. Employee salary ranking (top 10)
SELECT emp_name, salary
FROM Employees
ORDER BY salary DESC
LIMIT 10;


-- 13. Number of orders placed by each customer
SELECT c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM Customers c
JOIN Orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC;


-- 14. Customers whose spending is above average
SELECT c.customer_name,
       SUM(oi.quantity * p.price) AS total_spending
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
GROUP BY c.customer_name
HAVING total_spending >
(
    SELECT AVG(total_spending)
    FROM
    (
        SELECT SUM(oi.quantity * p.price) AS total_spending
        FROM Orders o
        JOIN Order_Items oi ON o.order_id = oi.order_id
        JOIN Products p ON oi.product_id = p.product_id
        GROUP BY o.customer_id
    ) AS customer_avg
);


-- 15. Revenue by department city (employee distribution insight)
SELECT e.city,
       COUNT(e.emp_id) AS employee_count,
       AVG(e.salary) AS avg_salary
FROM Employees e
GROUP BY e.city
ORDER BY employee_count DESC;
